# Generated by Django 4.2.28 on 2026-03-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_delaymodel'),
        ('conductorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusModels',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_number', models.CharField(max_length=50, unique=True)),
                ('bus_route', models.CharField(max_length=200)),
                ('bus_status', models.CharField(choices=[('idle', 'Idle'), ('active', 'Active'), ('ended', 'Trip Ended')], default='idle', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bus_data',
            },
        ),
        migrations.CreateModel(
            name='ConductorModels',
            fields=[
                ('conductor_id', models.AutoField(primary_key=True, serialize=False)),
                ('conductor_name', models.CharField(max_length=100)),
                ('conductor_phone', models.CharField(max_length=15)),
                ('conductor_email', models.EmailField(max_length=254)),
                ('conductor_password', models.CharField(max_length=100)),
                ('conductor_address', models.TextField()),
                ('conductor_image', models.ImageField(blank=True, null=True, upload_to='conductor/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conductor_data',
            },
        ),
        migrations.AlterModelTable(
            name='qrmodels',
            table='qrcode_data',
        ),
        migrations.CreateModel(
            name='PickupDropEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('pickup', 'Pickup'), ('drop', 'Drop')], max_length=50)),
                ('location_latitude', models.FloatField(null=True)),
                ('location_longitude', models.FloatField(null=True)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='conductorapp.busmodels')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_drop_events', to='adminapp.childmodels')),
            ],
            options={
                'db_table': 'pickup_drop_event',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='BusRouteModels',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=200)),
                ('route_stops', models.JSONField(help_text='Array of stops with lat, lng, name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='conductorapp.busmodels')),
            ],
            options={
                'db_table': 'bus_route_data',
            },
        ),
        migrations.AddField(
            model_name='busmodels',
            name='conductor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='conductorapp.conductormodels'),
        ),
        migrations.CreateModel(
            name='BusLocationModels',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0)),
                ('heading', models.FloatField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='conductorapp.busmodels')),
            ],
            options={
                'db_table': 'bus_location_data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
