# Generated by Django 4.2.28 on 2026-03-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductorapp', '0002_busmodels_conductormodels_alter_qrmodels_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmodels',
            name='bus_class',
            field=models.CharField(blank=True, help_text='Grade/class assigned to this bus', max_length=5, null=True),
        ),
    ]
